### ISSUE TITLE
可以设置滚动方向吗

### ISSUE THREAD

**Issue by wushange** [ziwenL/SrcScrollFrameLayout#3]
可以设置滚动方向吗 比如垂直滚动时 是从上往下 而不是从下网上

**Comment by ziwenL** [comment]
目前是未支持该功能的，您可以根据业务需求自行调整源码，难度不大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ziwenL/SrcScrollFrameLayout"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午5:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ziwenL/SrcScrollFrameLayout] 可以设置滚动方向吗 (#3)





 
可以设置滚动方向吗 比如垂直滚动时 是从上往下 而不是从下网上

**Comment by wushange** [comment]
> 目前是未支持该功能的，您可以根据业务需求自行调整源码，难度不大
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ziwenL/SrcScrollFrameLayout" ***@***.***&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:00 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[ziwenL/SrcScrollFrameLayout] 可以设置滚动方向吗 (#3) 可以设置滚动方向吗 比如垂直滚动时 是从上往下 而不是从下网上 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢你得回复， 已经在你基础上修改好了。
